### ISSUE TITLE
Wildcard SSL Cert 

### ISSUE THREAD

**Issue by travisneuber** [lithnet/access-manager#101]
I'm trying to set the SSL cert during setup/config, and I've installed a wildcard SSL cert we have for our domain via the instructions (installing into the personal directory), however the config, when trying to 'search, doesn't find any suitable SSL certs.

Any help is appreciated.

**Comment by sylwester-majcher** [comment]
Did you saved changes and stop and start AMS service?
Did the cert you put into machine store?
Did your cert have alternative name as dns name for the server?


Pozdrawiam
Sylwek
________________________________
Od: travisneuber ***@***.***>
Wysłane: Friday, June 4, 2021 8:01:57 PM
Do: lithnet/access-manager ***@***.***>
DW: Subscribed ***@***.***>
Temat: [lithnet/access-manager] Wildcard SSL Cert (#101)


I'm trying to set the SSL cert during setup/config, and I've installed a wildcard SSL cert we have for our domain via the instructions (installing into the personal directory), however the config, when trying to 'search, doesn't find any suitable SSL certs.

Any help is appreciated.

**Comment by jaysnrye** [comment]
Hi @travisneuber 

Please ensure you have placed the certificate in the machines personal store, not the user personal store. You can access the machines certificate store by typing certlm.msc at a command prompt.
For good measure you can restart the AMS service then select the certificate on the web hosting tab in AMS.

https://github.com/lithnet/access-manager/wiki/Installing-the-Access-Manager-Service

You should consider using a dedicated certificate for Access Manager instead of a wildcard certificate for security reasons. If any of yours services are compromised you risk opening Access Manager to attack too. While not required, it is recommended to use a dedicated certificate for high value assets.
