### ISSUE TITLE
[HELP] Authentication issue with OIDC and Azure AD

### ISSUE THREAD

**Issue by Luckysena** [lithnet/access-manager#113]
### [HELP] Authentication issue with OIDC and Azure AD
Hello,

I have set up Lithnet to run on a web server and have configured authentication using this documentation: https://github.com/lithnet/access-manager/wiki/Setting-up-authentication-with-Azure-AD

When connecting to my tenant's auth directly (e.g. lithnet.io/auth) I receive this error upon trying to authenticate from the access-manager-service.txt logs:
2021-07-27 12:45:55.4268|ERROR|Lithnet.AccessManager.Service.AppSettings.OidcAuthenticationProvider|The authentication provider returned an error
System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.

Additionally if I try to just visit the base tenant url (e.g. lithnet.io) I receive a 404 on the page which I expected would redirect to the login page. Attached auth error in the logs:
[lithnetAuthError.txt](https://github.com/lithnet/access-manager/files/6887419/lithnetAuthError.txt)

After days of trying to figure out the bug I've come to the conclusion that I must have configured something incorrectly, I'm just not sure what it would be. Any help would be much appreciated.

**Comment by ScottHuman** [comment]
Hi @Luckysena - happy to help, need a bit more information to dig into this.

In the AMS configuration UI authentication page, have you set your issuer/authority to 
https://login.microsoftonline.com/domain.com ?

(where domain.com is your Azure AD primary tenant domain name)

**Comment by Luckysena** [comment]
Hi @ScottHuman , thanks for the quick reply. A bit new to setting up auth, so please bear with me. 

Within the AMS config UI currently I have https://login.microsoftonline.com/useweb123.mhf.mhc, where useweb123 is the server name and mhf.mhc is the domain. I had configured this within Azure AD and have the client id and secret from Azure in the AMS UI.

**Comment by ryannewington** [comment]
Hi

Domain.com should be the primary domain name of your azure tenant, not the name of the AMS server. 

Eg lithnet.onmicrosoft.com
Or lithnet.io

**Comment by Luckysena** [comment]
Thanks for the clarification, I've added the appropriate domain name now. When I access the AMS server with the base url I receive a:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'eb250de3-582f-4440-80c0-67b4a8739893'

When I go to /auth I still get the same authentication error as in my original question.

From what I understand the first error is coming up because my request didn't include /auth, is this a correct assumption? Or is something misconfigured within Azure AD?

Thanks for all the help so far!

**Comment by ryannewington** [comment]
This error means that AMS has told azure AD that once the user has been authenticated, return them to https://hostname.used.in.browser/auth. However Azure AD does not have this URL listed in its list of allowed reply URLs

This URL must match the reply URL set up in Azure AD. Note that it is based on the URL the user types in the browser. Not what the server thinks its name is. 

If the user accesses the server via http://localhost then you must have a reply URL for https://localhost/auth. If they access it via https://alias.server.com then we need another reply URL for this. 

The /auth component is required for every URL set up in Azure because that is where AzureAD sends the authentication response. You don't need to visit this URL yourself.

**Comment by Luckysena** [comment]
Thanks for all the help, it seems like there was a typo in the server name for the reply URL.
