### ISSUE TITLE
We are unable to generate password

### ISSUE THREAD

**Issue by supporteh** [lithnet/access-manager#153]
We are unable to generate password Enabled with LAPS, it is showing as no administrator account found. Please support on this

**Comment by ryannewington** [comment]
Hi @supporteh 

Can you provide a bit more detail about what you are experiencing. Are you using the Lithnet Agent to manage the LAPS password, and that is not working? Or are you trying to access a LAPS password with the Access Manager web app, and it's saying the computer has no password?

**Comment by supporteh** [comment]
Hi Ryan, thanks for your response. we are trying to get LAPS password with access manager web app
![image](https://user-images.githubusercontent.com/91018614/163337552-3607e543-47e3-4200-bf93-c8e1bd23022e.png)

**Comment by ryannewington** [comment]
This means that the AMS service account does not have permission to read the LAPS passwords from active directory. 

Step 1 of the following guide will help you with configuring the appropriate AD permission

https://docs.lithnet.io/projects/access-manager/en/stable/deploying_features/Setting-up-Microsoft-LAPS.html

**Comment by supporteh** [comment]
Hi Ryan, thanks for your support. it is working well. 
one more query, how can i see the option for password history
![image](https://user-images.githubusercontent.com/91018614/163353881-0bdc8c25-bd89-4e3e-b8ab-49d50133a87a.png)

**Comment by ryannewington** [comment]
@supporteh 

LAPS history requires an Enterprise edition license, and also requires you to use the Lithnet Access Manager agent instead of the Microsoft LAPS agent (https://docs.lithnet.io/projects/access-manager/en/stable/deploying_features/Setting-up-password-encryption-and-history.html)

If you want to inquire about Enterprise Edition pricing, reach out to the team using the contact form at the bottom of this page https://lithnet.io/products/access-manager
