### ISSUE TITLE
Version query 

### ISSUE THREAD

**Issue by Afsars12** [lithnet/access-manager#169]
Hi Team,

We have some questions about the Version and its supportability.

1) Does version 1.0.7941.0 (Standard edition) currently supported? If we purchase the enterprise license does this need to be v2.0 or can we continue with 1.0.7941.0? 

2) is it mandatory to have an SQL server, for an upgrade from 1.0 to 2.0?

3)  How long is the 1.0.7941.0 supported?

4) There is a security tab option shown on this page. Is it available and supported only in the Enterprise version?

Regards
Afsar

**Comment by ryannewington** [comment]
Hi @Afsars12 

1. There's no formal support for standard edition. Enterprise edition customers are supported for major versions for 18 months after the next major version comes out. So if we released v2 tomorrow, you'd be covered for support for 18 months from tomorrow. We'll support minor releases, but if there is a problem or a bug, it will always be fixed in the latest minor version of the major release you are on. Eg if you were on 1.0.7930, and we issued a bug fix for you, that would come out in 1.0.7942.
2. Yes, [SQL Server is a requirement for v2](https://docs.lithnet.io/ams/installation/installing-the-access-manager-server/sql-installation-options), but it comes bundled with SQL express, which is suitable for small - medium sized environments. You can also use Azure SQL or Amason RDS SQL.
3. Addressed in point one above
4. The security page is only in v2, and it does not require enterprise edition.

You're welcome to send us an email to sales@lithnet.io if you have additional questions, or would like to get a quote for Enterprise edition. We can also supply you the full support agreement if that is helpful.

**Comment by ryannewington** [comment]
You can [download the current v2 preview here](https://github.com/lithnet/access-manager/releases/tag/v2.0.8904-preview2), and the [details for upgrading are located here](https://docs.lithnet.io/ams/installation/upgrading-from-v1)
