### ISSUE TITLE
[Help] how to grant RapidLaps access trough smartphone

### ISSUE THREAD

**Issue by SandBot59302** [lithnet/access-manager#239]
If I scan the QR-Code with my smartphone, I get redirected to the AMS webservice, which works just fine. But I can't accept the RapidLaps request because I'm unauthorized. 

The Problem is, I don't get any prompt to verify myself with my Windows credentials. 

In our environment, we only use windows authentication because we don't have an Azure AD or any other platform like octa. 

Is there any way to accept the RapidLaps request with a device which is not connect to the active directory or domain? 
![IMG_9670](https://github.com/user-attachments/assets/4d70062a-f336-49b0-a073-79240c6e5b03)

**Comment by ryannewington** [comment]
@SandBot59302 I'm not sure whats going on but your browser should be promoting you for windows auth. The fact that it's taking you straight to unauthorised means that the browser must have windows auth disabled and isn't even trying. 

It might be worth trying another browser? Which OS and browser do you see this problem on?

**Comment by SandBot59302** [comment]
Hi,  

so I try to use RapidLAPS on my Client and scan the QR-Code with my iPhone and then the links opens in Safari. I am using the latest update of Lithnet. 

If I logon to the website directly with my windows client I get the authentication prompt as usually and i can enter the passcode.

**Comment by ryannewington** [comment]
@SandBot59302 We've done some digging, and while it looks like iOS does support kerberos, it requires a managed profile be deployed to the device for this to work. It doesnt support NTLM over Negotiate for some reason.

In order to get this working, we've added NTLM support to the web app. 

You'll need to download v3.0.1227 available here: [https://packages.lithnet.io/win/access-manager-service/v3.0/x64/latest](https://packages.lithnet.io/win/access-manager-service/v3.0/x64/latest.lnk)

From the authentcation page of the configuration app, change the auth method to "Negotiate or NTLM"

Please let me know if this resolves the issue for you.

**Comment by SandBot59302** [comment]
Hi, that's working perfectly fine! Thank you!
