### ISSUE TITLE
Ability to request password/access that has to go thru approval process

### ISSUE THREAD

**Issue by PrzemyslawKlys** [lithnet/access-manager#9]
I know this is a big one - but maybe as something for the future - It would be cool if user could request access and someone would need to approve it before he is given LAPS or JIT access.

**Comment by ryannewington** [comment]
It is a big one, and I've thought about this a bit. I came to the conclusion that I'm not going to turn this into a fully fledged PAM tool. 

My goal is simply to reduce lateral movement capability by removing common permanent admins from computers. To achieve that goal, the tool needs to provide a low-friction mechanism for those that have admin rights on computers today through membership in the local admins group, to move to LAPS or JIT, but keep whatever access they have today.

I reserve the right to change my mind on this later 😆 but for now, we're going with the simple pre-approved authorization, rather than gated authorization.
